src/Entity/Student.php
<?php

namespace App\Entity;

use App\Repository\StudentRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=StudentRepository::class)
 */
class Student
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    private $Nce;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $FirstName;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $LastName;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Email;

    /**
     * @ORM\ManyToOne(targetEntity=Classroom::class, inversedBy="student")
     */
    private $classroom;

    /**
     * @return mixed
     */
    public function getNce()
    {
        return $this->Nce;
    }

    /**
     * @param mixed $Nce
     */
    public function setNce($Nce): void
    {
        $this->Nce = $Nce;
    }


    public function getFirstName(): ?string
    {
        return $this->FirstName;
    }

    public function setFirstName(string $FirstName): self
    {
        $this->FirstName = $FirstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->LastName;
    }

    public function setLastName(string $LastName): self
    {
        $this->LastName = $LastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getClassroom(): ?Classroom
    {
        return $this->classroom;
    }

    public function setClassroom(?Classroom $classroom): self
    {
        $this->classroom = $classroom;

        return $this;
    }

}

src/Form/StudentType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class StudentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Nce')

            ->add('FirstName')
            ->add('LastName')
            ->add('Email')
            ->add('classroom')


            ->add("add", SubmitType::class)


        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            // Configure your form options here
        ]);
    }
}

src/Controller/StudentController.php
<?php

namespace App\Controller;

use App\Entity\Classroom;
use App\Entity\Student;
use App\Form\StudentType;
use Doctrine\Persistence\ObjectRepository;
use http\Env\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\HttpFoundation\HttpFoundationRequestHandler;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class StudentController extends AbstractController
{
    /**
     * @var ObjectManger
     */
    private $em;

    /**
     * @Route("/student", name="student")
     */
    public function index(): Response
    {
        return $this->render('student/index.html.twig', [
            'controller_name' => 'StudentController',
        ]);
    }
    public function __construct( ObjectRepository $repository, ObjectManger $em)
{
$this->$repository =$repository;
    $this->em = $em;
}
    /**
     * @Route("/listeStudent", name="listeStudent")
     */
    public function listStudents()
    {
        $listStudent = $this->getDoctrine()->getRepository(Student::class)->findAll();
        return $this->render("student/listStudent.html.twig", array('students' => $listStudent));

    }

    /**
     * @Route("/addStudent", name="addStudent")
     */

    public function addStudent(\Symfony\Component\HttpFoundation\Request $request)
    {
        $Student = new Student();
        $form = $this->createForm(StudentType::class, $Student);
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($Student);
            $em->flush();
            return $this->redirectToRoute("listeStudent");

        }
        return $this->render("student/addStudent.html.twig", array("formStudent" => $form->createView()));


    }

    /**
     * @Route("/updateStudent/{id}", name="updateStudent")
     */
    public function updateStudent(\Symfony\Component\HttpFoundation\Request $request,$id)
    {
        $Student = $this->getDoctrine()->getRepository(Student::class )->find($id);
        $form = $this->createForm(StudentType::class, $Student);
$form->handleRequest($request);
if ($form->isSubmitted()){
    $em=$this->getDoctrine()->getManager();
    $em->flush();
    return$this->redirectToRoute("listeStudent");

}
return $this->render("student/updateStudent.html.twig",array("formStudent"=>$form->createView()));

    }
    /**
     * @Route("/deleteStudent/{id}", name="removeStudent")
     */
    public function deleteStudent($id): \Symfony\Component\HttpFoundation\RedirectResponse
    {
        $Student = $this->getDoctrine()->getRepository(Student::class)->find($id);
        $em=$this->getDoctrine()->getManager();
        $em->remove($Student);
        $em->flush();
        return $this->redirectToRoute("listeStudent");
    }
}

templates/student/addStudent.html.twig
{% extends "base.html.twig" %}
{% block head   %}
{% endblock%}
{% block body %}
{{ form(formStudent) }}
{% endblock  %}

templates/student/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello StudentController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 2em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/xampp/htdocs/Espritclub/src/Controller/StudentController.php'|file_link(0) }}">src/Controller/StudentController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/xampp/htdocs/Espritclub/templates/student/index.html.twig'|file_link(0) }}">templates/student/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/student/listStudent.html.twig
{% extends "base.html.twig" %}
{% block head   %}
{% endblock%}
{% block body %}
    <table class="table table-dark table-striped">

    <tr>
        <td>Nce</td>
        <td>FirstName</td>
        <td>LastName</td>
        <td>Email</td>
        <td>Action</td>
        <td>classeRoom</td>

    </tr>
    {% for i in students %}
        <tr>
            <td>{{ i.nce }}</td>
            <td>{{ i.FirstName }}</td>
            <td>{{ i.LastName }}</td>
            <td>{{ i.Email }}</td>
            <td>{{ i.classroom}}</td>
           <td><a href="{{ path("updateStudent",{'id':i.Nce}) }}">update</a> <a href="{{ path('removeStudent',{'id':i.Nce}) }}">delete</a></td>



        </tr>
    {% endfor %}
</table>
{% endblock  %}

templates/student/updateStudent.html.twig
{{ form(formStudent) }}